# Generated by Django 6.0.1 on 2026-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="todo_app.category", verbose_name="categories"
            ),
        ),
    ]
