# Generated by Django 6.0.1 on 2026-02-01 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_alter_todo_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="categories",
        ),
        migrations.AddField(
            model_name="todo",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="todo_app.category",
                verbose_name="categories",
            ),
        ),
    ]
