# Generated by Django 6.0.1 on 2026-02-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_remove_todo_categories_todo_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="categories",
        ),
        migrations.AddField(
            model_name="todo",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="todo_app.category", verbose_name="categories"
            ),
        ),
    ]
